new wifi tcp streaming

diff --git a/.github/workflows/ZeDMD.yml b/.github/workflows/ZeDMD.yml
--- a/.github/workflows/ZeDMD.yml
+++ b/.github/workflows/ZeDMD.yml
@@ -23,6 +23,15 @@ jobs:
           TAG="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}"
           echo "${TAG}"
           echo "tag=${TAG}" >> $GITHUB_OUTPUT
+      - name: Check git tag
+        if: startsWith(github.ref, 'refs/tags/v')
+        run: |
+          GIT_TAG="${GITHUB_REF#refs/tags/}"
+          EXPECTED_TAG="v${{ steps.version.outputs.tag }}"
+          if [[ "${GIT_TAG}" != "${EXPECTED_TAG}" ]]; then
+            echo "Error: Git tag (${GIT_TAG}) does not match version from version.h (v${{ steps.version.outputs.tag }})"
+            exit 1
+          fi
 
   pio-run:
     runs-on: ubuntu-latest
@@ -88,7 +97,7 @@ jobs:
     steps:
       - uses: actions/download-artifact@v4
       - name: Package
-        if: startsWith(github.ref, 'refs/tags/')
+        if: startsWith(github.ref, 'refs/tags/v')
         run: |
             cd ZeDMD-128x32
             echo "${{ needs.version.outputs.tag }}" > version.txt
@@ -126,7 +135,7 @@ jobs:
             cd ..
       - name: Release
         uses: softprops/action-gh-release@v1
-        if: startsWith(github.ref, 'refs/tags/')
+        if: startsWith(github.ref, 'refs/tags/v')
         with:
           draft: true
           files: |
